# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='parents',
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The organizations that contain this organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='decisions.Organization'),
        ),
        migrations.AlterField(
            model_name='action',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event this action is related to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='decisions.Event'),
        ),
    ]
